#include "DryIce2Common.cginc"
// Created by David Gallardo - xjorma/2020
// License Creative Commons Attribution-NonCommercial-ShareAlike 3.0

// Pressure solver 1st interation

// Impired by https://www.shadertoy.com/view/MdSczK by Trirop
// Since in shadertoy we don't have countless pass we need to do many pass at once.


// code generated by :
/*
#include <iostream>

const int tabSize = 48;

std::int64_t divTab[tabSize][tabSize];
std::int64_t preTab[tabSize][tabSize];


void recurse(int x, int y, int level)
{
    level--;
    divTab[x][y] += std::int64_t(1) << std::int64_t(level * 2);
    if (level)
    {
        recurse(x - 1, y, level);
        recurse(x + 1, y, level);
        recurse(x, y - 1, level);
        recurse(x, y + 1, level);
    }
    else
    {
        preTab[x - 1][y]++;
        preTab[x + 1][y]++;
        preTab[x][y - 1]++;
        preTab[x][y + 1]++;
    }
}

void clear(std::int64_t (&tab)[tabSize][tabSize])
{
    for (int x = 0; x < tabSize; x++)
    {
        for (int y = 0; y < tabSize; y++)
        {
            tab[x][y] = 0;
        }
    }
}

void output(const char *functionName, std::int64_t(&tab)[tabSize][tabSize], std::int64_t multiplier)
{
    std::int64_t total = 0;
    for (int x = 0; x < tabSize; x++)
    {
        for (int y = 0; y < tabSize; y++)
        {
            if (tab[x][y])
            {
                total += tab[x][y];
                std::cout << "\tp += " << tab[x][y] << ".*" << functionName << "(" << x - tabSize / 2 << ", " << y - tabSize / 2 << ");\n";
            }
        }
    }
    total *= multiplier;
    std::cout << "\treturn\tp / " << total << ".;\n";
}

int main()
{
    clear(divTab);
    clear(preTab);
    recurse(tabSize / 2, tabSize / 2, 10);
    output("div", divTab, 2);
    output("pre", preTab, 1);
}
*/

float div(int x, int y, vec2 gl_FragCoord)
{
    return texelFetch(iChannel0, (ivec2(gl_FragCoord.xy) + ivec2(x, y)) / float2(_ScreenParams.xy)).x;
}

float getDiv(vec2 gl_FragCoord)
{
    float p = 0.;
    p += 1. * div(-9, 0, gl_FragCoord);
    p += 9. * div(-8, -1, gl_FragCoord);
    p += 4. * div(-8, 0, gl_FragCoord);
    p += 9. * div(-8, 1, gl_FragCoord);
    p += 36. * div(-7, -2, gl_FragCoord);
    p += 32. * div(-7, -1, gl_FragCoord);
    p += 97. * div(-7, 0, gl_FragCoord);
    p += 32. * div(-7, 1, gl_FragCoord);
    p += 36. * div(-7, 2, gl_FragCoord);
    p += 84. * div(-6, -3, gl_FragCoord);
    p += 112. * div(-6, -2, gl_FragCoord);
    p += 436. * div(-6, -1, gl_FragCoord);
    p += 320. * div(-6, 0, gl_FragCoord);
    p += 436. * div(-6, 1, gl_FragCoord);
    p += 112. * div(-6, 2, gl_FragCoord);
    p += 84. * div(-6, 3, gl_FragCoord);
    p += 126. * div(-5, -4, gl_FragCoord);
    p += 224. * div(-5, -3, gl_FragCoord);
    p += 1092. * div(-5, -2, gl_FragCoord);
    p += 1280. * div(-5, -1, gl_FragCoord);
    p += 2336. * div(-5, 0, gl_FragCoord);
    p += 1280. * div(-5, 1, gl_FragCoord);
    p += 1092. * div(-5, 2, gl_FragCoord);
    p += 224. * div(-5, 3, gl_FragCoord);
    p += 126. * div(-5, 4, gl_FragCoord);
    p += 126. * div(-4, -5, gl_FragCoord);
    p += 280. * div(-4, -4, gl_FragCoord);
    p += 1694. * div(-4, -3, gl_FragCoord);
    p += 2752. * div(-4, -2, gl_FragCoord);
    p += 6656. * div(-4, -1, gl_FragCoord);
    p += 6464. * div(-4, 0, gl_FragCoord);
    p += 6656. * div(-4, 1, gl_FragCoord);
    p += 2752. * div(-4, 2, gl_FragCoord);
    p += 1694. * div(-4, 3, gl_FragCoord);
    p += 280. * div(-4, 4, gl_FragCoord);
    p += 126. * div(-4, 5, gl_FragCoord);
    p += 84. * div(-3, -6, gl_FragCoord);
    p += 224. * div(-3, -5, gl_FragCoord);
    p += 1694. * div(-3, -4, gl_FragCoord);
    p += 3520. * div(-3, -3, gl_FragCoord);
    p += 11016. * div(-3, -2, gl_FragCoord);
    p += 16128. * div(-3, -1, gl_FragCoord);
    p += 24608. * div(-3, 0, gl_FragCoord);
    p += 16128. * div(-3, 1, gl_FragCoord);
    p += 11016. * div(-3, 2, gl_FragCoord);
    p += 3520. * div(-3, 3, gl_FragCoord);
    p += 1694. * div(-3, 4, gl_FragCoord);
    p += 224. * div(-3, 5, gl_FragCoord);
    p += 84. * div(-3, 6, gl_FragCoord);
    p += 36. * div(-2, -7, gl_FragCoord);
    p += 112. * div(-2, -6, gl_FragCoord);
    p += 1092. * div(-2, -5, gl_FragCoord);
    p += 2752. * div(-2, -4, gl_FragCoord);
    p += 11016. * div(-2, -3, gl_FragCoord);
    p += 21664. * div(-2, -2, gl_FragCoord);
    p += 47432. * div(-2, -1, gl_FragCoord);
    p += 59712. * div(-2, 0, gl_FragCoord);
    p += 47432. * div(-2, 1, gl_FragCoord);
    p += 21664. * div(-2, 2, gl_FragCoord);
    p += 11016. * div(-2, 3, gl_FragCoord);
    p += 2752. * div(-2, 4, gl_FragCoord);
    p += 1092. * div(-2, 5, gl_FragCoord);
    p += 112. * div(-2, 6, gl_FragCoord);
    p += 36. * div(-2, 7, gl_FragCoord);
    p += 9. * div(-1, -8, gl_FragCoord);
    p += 32. * div(-1, -7, gl_FragCoord);
    p += 436. * div(-1, -6, gl_FragCoord);
    p += 1280. * div(-1, -5, gl_FragCoord);
    p += 6656. * div(-1, -4, gl_FragCoord);
    p += 16128. * div(-1, -3, gl_FragCoord);
    p += 47432. * div(-1, -2, gl_FragCoord);
    p += 92224. * div(-1, -1, gl_FragCoord);
    p += 163476. * div(-1, 0, gl_FragCoord);
    p += 92224. * div(-1, 1, gl_FragCoord);
    p += 47432. * div(-1, 2, gl_FragCoord);
    p += 16128. * div(-1, 3, gl_FragCoord);
    p += 6656. * div(-1, 4, gl_FragCoord);
    p += 1280. * div(-1, 5, gl_FragCoord);
    p += 436. * div(-1, 6, gl_FragCoord);
    p += 32. * div(-1, 7, gl_FragCoord);
    p += 9. * div(-1, 8, gl_FragCoord);
    p += 1. * div(0, -9, gl_FragCoord);
    p += 4. * div(0, -8, gl_FragCoord);
    p += 97. * div(0, -7, gl_FragCoord);
    p += 320. * div(0, -6, gl_FragCoord);
    p += 2336. * div(0, -5, gl_FragCoord);
    p += 6464. * div(0, -4, gl_FragCoord);
    p += 24608. * div(0, -3, gl_FragCoord);
    p += 59712. * div(0, -2, gl_FragCoord);
    p += 163476. * div(0, -1, gl_FragCoord);
    p += 409744. * div(0, 0, gl_FragCoord);
    p += 163476. * div(0, 1, gl_FragCoord);
    p += 59712. * div(0, 2, gl_FragCoord);
    p += 24608. * div(0, 3, gl_FragCoord);
    p += 6464. * div(0, 4, gl_FragCoord);
    p += 2336. * div(0, 5, gl_FragCoord);
    p += 320. * div(0, 6, gl_FragCoord);
    p += 97. * div(0, 7, gl_FragCoord);
    p += 4. * div(0, 8, gl_FragCoord);
    p += 1. * div(0, 9, gl_FragCoord);
    p += 9. * div(1, -8, gl_FragCoord);
    p += 32. * div(1, -7, gl_FragCoord);
    p += 436. * div(1, -6, gl_FragCoord);
    p += 1280. * div(1, -5, gl_FragCoord);
    p += 6656. * div(1, -4, gl_FragCoord);
    p += 16128. * div(1, -3, gl_FragCoord);
    p += 47432. * div(1, -2, gl_FragCoord);
    p += 92224. * div(1, -1, gl_FragCoord);
    p += 163476. * div(1, 0, gl_FragCoord);
    p += 92224. * div(1, 1, gl_FragCoord);
    p += 47432. * div(1, 2, gl_FragCoord);
    p += 16128. * div(1, 3, gl_FragCoord);
    p += 6656. * div(1, 4, gl_FragCoord);
    p += 1280. * div(1, 5, gl_FragCoord);
    p += 436. * div(1, 6, gl_FragCoord);
    p += 32. * div(1, 7, gl_FragCoord);
    p += 9. * div(1, 8, gl_FragCoord);
    p += 36. * div(2, -7, gl_FragCoord);
    p += 112. * div(2, -6, gl_FragCoord);
    p += 1092. * div(2, -5, gl_FragCoord);
    p += 2752. * div(2, -4, gl_FragCoord);
    p += 11016. * div(2, -3, gl_FragCoord);
    p += 21664. * div(2, -2, gl_FragCoord);
    p += 47432. * div(2, -1, gl_FragCoord);
    p += 59712. * div(2, 0, gl_FragCoord);
    p += 47432. * div(2, 1, gl_FragCoord);
    p += 21664. * div(2, 2, gl_FragCoord);
    p += 11016. * div(2, 3, gl_FragCoord);
    p += 2752. * div(2, 4, gl_FragCoord);
    p += 1092. * div(2, 5, gl_FragCoord);
    p += 112. * div(2, 6, gl_FragCoord);
    p += 36. * div(2, 7, gl_FragCoord);
    p += 84. * div(3, -6, gl_FragCoord);
    p += 224. * div(3, -5, gl_FragCoord);
    p += 1694. * div(3, -4, gl_FragCoord);
    p += 3520. * div(3, -3, gl_FragCoord);
    p += 11016. * div(3, -2, gl_FragCoord);
    p += 16128. * div(3, -1, gl_FragCoord);
    p += 24608. * div(3, 0, gl_FragCoord);
    p += 16128. * div(3, 1, gl_FragCoord);
    p += 11016. * div(3, 2, gl_FragCoord);
    p += 3520. * div(3, 3, gl_FragCoord);
    p += 1694. * div(3, 4, gl_FragCoord);
    p += 224. * div(3, 5, gl_FragCoord);
    p += 84. * div(3, 6, gl_FragCoord);
    p += 126. * div(4, -5, gl_FragCoord);
    p += 280. * div(4, -4, gl_FragCoord);
    p += 1694. * div(4, -3, gl_FragCoord);
    p += 2752. * div(4, -2, gl_FragCoord);
    p += 6656. * div(4, -1, gl_FragCoord);
    p += 6464. * div(4, 0, gl_FragCoord);
    p += 6656. * div(4, 1, gl_FragCoord);
    p += 2752. * div(4, 2, gl_FragCoord);
    p += 1694. * div(4, 3, gl_FragCoord);
    p += 280. * div(4, 4, gl_FragCoord);
    p += 126. * div(4, 5, gl_FragCoord);
    p += 126. * div(5, -4, gl_FragCoord);
    p += 224. * div(5, -3, gl_FragCoord);
    p += 1092. * div(5, -2, gl_FragCoord);
    p += 1280. * div(5, -1, gl_FragCoord);
    p += 2336. * div(5, 0, gl_FragCoord);
    p += 1280. * div(5, 1, gl_FragCoord);
    p += 1092. * div(5, 2, gl_FragCoord);
    p += 224. * div(5, 3, gl_FragCoord);
    p += 126. * div(5, 4, gl_FragCoord);
    p += 84. * div(6, -3, gl_FragCoord);
    p += 112. * div(6, -2, gl_FragCoord);
    p += 436. * div(6, -1, gl_FragCoord);
    p += 320. * div(6, 0, gl_FragCoord);
    p += 436. * div(6, 1, gl_FragCoord);
    p += 112. * div(6, 2, gl_FragCoord);
    p += 84. * div(6, 3, gl_FragCoord);
    p += 36. * div(7, -2, gl_FragCoord);
    p += 32. * div(7, -1, gl_FragCoord);
    p += 97. * div(7, 0, gl_FragCoord);
    p += 32. * div(7, 1, gl_FragCoord);
    p += 36. * div(7, 2, gl_FragCoord);
    p += 9. * div(8, -1, gl_FragCoord);
    p += 4. * div(8, 0, gl_FragCoord);
    p += 9. * div(8, 1, gl_FragCoord);
    p += 1. * div(9, 0, gl_FragCoord);
    return  p / 1048576.;
}

float pre(int x, int y, vec2 gl_FragCoord)
{
    return texelFetch(iChannel1, (ivec2(gl_FragCoord.xy) + ivec2(x, y)) / float2(_ScreenParams.xy)).x;
}

float getPre(vec2 gl_FragCoord)
{
    float p = 0.;
    p += 1. * pre(-10, 0, gl_FragCoord);
    p += 10. * pre(-9, -1, gl_FragCoord);
    p += 10. * pre(-9, 1, gl_FragCoord);
    p += 45. * pre(-8, -2, gl_FragCoord);
    p += 100. * pre(-8, 0, gl_FragCoord);
    p += 45. * pre(-8, 2, gl_FragCoord);
    p += 120. * pre(-7, -3, gl_FragCoord);
    p += 450. * pre(-7, -1, gl_FragCoord);
    p += 450. * pre(-7, 1, gl_FragCoord);
    p += 120. * pre(-7, 3, gl_FragCoord);
    p += 210. * pre(-6, -4, gl_FragCoord);
    p += 1200. * pre(-6, -2, gl_FragCoord);
    p += 2025. * pre(-6, 0, gl_FragCoord);
    p += 1200. * pre(-6, 2, gl_FragCoord);
    p += 210. * pre(-6, 4, gl_FragCoord);
    p += 252. * pre(-5, -5, gl_FragCoord);
    p += 2100. * pre(-5, -3, gl_FragCoord);
    p += 5400. * pre(-5, -1, gl_FragCoord);
    p += 5400. * pre(-5, 1, gl_FragCoord);
    p += 2100. * pre(-5, 3, gl_FragCoord);
    p += 252. * pre(-5, 5, gl_FragCoord);
    p += 210. * pre(-4, -6, gl_FragCoord);
    p += 2520. * pre(-4, -4, gl_FragCoord);
    p += 9450. * pre(-4, -2, gl_FragCoord);
    p += 14400. * pre(-4, 0, gl_FragCoord);
    p += 9450. * pre(-4, 2, gl_FragCoord);
    p += 2520. * pre(-4, 4, gl_FragCoord);
    p += 210. * pre(-4, 6, gl_FragCoord);
    p += 120. * pre(-3, -7, gl_FragCoord);
    p += 2100. * pre(-3, -5, gl_FragCoord);
    p += 11340. * pre(-3, -3, gl_FragCoord);
    p += 25200. * pre(-3, -1, gl_FragCoord);
    p += 25200. * pre(-3, 1, gl_FragCoord);
    p += 11340. * pre(-3, 3, gl_FragCoord);
    p += 2100. * pre(-3, 5, gl_FragCoord);
    p += 120. * pre(-3, 7, gl_FragCoord);
    p += 45. * pre(-2, -8, gl_FragCoord);
    p += 1200. * pre(-2, -6, gl_FragCoord);
    p += 9450. * pre(-2, -4, gl_FragCoord);
    p += 30240. * pre(-2, -2, gl_FragCoord);
    p += 44100. * pre(-2, 0, gl_FragCoord);
    p += 30240. * pre(-2, 2, gl_FragCoord);
    p += 9450. * pre(-2, 4, gl_FragCoord);
    p += 1200. * pre(-2, 6, gl_FragCoord);
    p += 45. * pre(-2, 8, gl_FragCoord);
    p += 10. * pre(-1, -9, gl_FragCoord);
    p += 450. * pre(-1, -7, gl_FragCoord);
    p += 5400. * pre(-1, -5, gl_FragCoord);
    p += 25200. * pre(-1, -3, gl_FragCoord);
    p += 52920. * pre(-1, -1, gl_FragCoord);
    p += 52920. * pre(-1, 1, gl_FragCoord);
    p += 25200. * pre(-1, 3, gl_FragCoord);
    p += 5400. * pre(-1, 5, gl_FragCoord);
    p += 450. * pre(-1, 7, gl_FragCoord);
    p += 10. * pre(-1, 9, gl_FragCoord);
    p += 1. * pre(0, -10, gl_FragCoord);
    p += 100. * pre(0, -8, gl_FragCoord);
    p += 2025. * pre(0, -6, gl_FragCoord);
    p += 14400. * pre(0, -4, gl_FragCoord);
    p += 44100. * pre(0, -2, gl_FragCoord);
    p += 63504. * pre(0, 0, gl_FragCoord);
    p += 44100. * pre(0, 2, gl_FragCoord);
    p += 14400. * pre(0, 4, gl_FragCoord);
    p += 2025. * pre(0, 6, gl_FragCoord);
    p += 100. * pre(0, 8, gl_FragCoord);
    p += 1. * pre(0, 10, gl_FragCoord);
    p += 10. * pre(1, -9, gl_FragCoord);
    p += 450. * pre(1, -7, gl_FragCoord);
    p += 5400. * pre(1, -5, gl_FragCoord);
    p += 25200. * pre(1, -3, gl_FragCoord);
    p += 52920. * pre(1, -1, gl_FragCoord);
    p += 52920. * pre(1, 1, gl_FragCoord);
    p += 25200. * pre(1, 3, gl_FragCoord);
    p += 5400. * pre(1, 5, gl_FragCoord);
    p += 450. * pre(1, 7, gl_FragCoord);
    p += 10. * pre(1, 9, gl_FragCoord);
    p += 45. * pre(2, -8, gl_FragCoord);
    p += 1200. * pre(2, -6, gl_FragCoord);
    p += 9450. * pre(2, -4, gl_FragCoord);
    p += 30240. * pre(2, -2, gl_FragCoord);
    p += 44100. * pre(2, 0, gl_FragCoord);
    p += 30240. * pre(2, 2, gl_FragCoord);
    p += 9450. * pre(2, 4, gl_FragCoord);
    p += 1200. * pre(2, 6, gl_FragCoord);
    p += 45. * pre(2, 8, gl_FragCoord);
    p += 120. * pre(3, -7, gl_FragCoord);
    p += 2100. * pre(3, -5, gl_FragCoord);
    p += 11340. * pre(3, -3, gl_FragCoord);
    p += 25200. * pre(3, -1, gl_FragCoord);
    p += 25200. * pre(3, 1, gl_FragCoord);
    p += 11340. * pre(3, 3, gl_FragCoord);
    p += 2100. * pre(3, 5, gl_FragCoord);
    p += 120. * pre(3, 7, gl_FragCoord);
    p += 210. * pre(4, -6, gl_FragCoord);
    p += 2520. * pre(4, -4, gl_FragCoord);
    p += 9450. * pre(4, -2, gl_FragCoord);
    p += 14400. * pre(4, 0, gl_FragCoord);
    p += 9450. * pre(4, 2, gl_FragCoord);
    p += 2520. * pre(4, 4, gl_FragCoord);
    p += 210. * pre(4, 6, gl_FragCoord);
    p += 252. * pre(5, -5, gl_FragCoord);
    p += 2100. * pre(5, -3, gl_FragCoord);
    p += 5400. * pre(5, -1, gl_FragCoord);
    p += 5400. * pre(5, 1, gl_FragCoord);
    p += 2100. * pre(5, 3, gl_FragCoord);
    p += 252. * pre(5, 5, gl_FragCoord);
    p += 210. * pre(6, -4, gl_FragCoord);
    p += 1200. * pre(6, -2, gl_FragCoord);
    p += 2025. * pre(6, 0, gl_FragCoord);
    p += 1200. * pre(6, 2, gl_FragCoord);
    p += 210. * pre(6, 4, gl_FragCoord);
    p += 120. * pre(7, -3, gl_FragCoord);
    p += 450. * pre(7, -1, gl_FragCoord);
    p += 450. * pre(7, 1, gl_FragCoord);
    p += 120. * pre(7, 3, gl_FragCoord);
    p += 45. * pre(8, -2, gl_FragCoord);
    p += 100. * pre(8, 0, gl_FragCoord);
    p += 45. * pre(8, 2, gl_FragCoord);
    p += 10. * pre(9, -1, gl_FragCoord);
    p += 10. * pre(9, 1, gl_FragCoord);
    p += 1. * pre(10, 0, gl_FragCoord);
    return  p / 1048576.;
}

void mainImage(out vec4 fragColor, in vec2 C)
{
    float div = getDiv(C);
    float p = getPre(C) - div;
    fragColor = vec4(p, div, vec2(1,1));
}